- hosts:
  - worker1
  - worker2

  gather_facts: true
  roles:
    - { role: ping, tags: [ 'ping' ] }
    - { role: whoami, tags: [ 'whoami' ] }
    - { role: k8s_cluster_create, tags: [ 'k8s_cluster_create' ] }
