- name: Started creating kubernetes cluster
  become: true
  become_user: root
  become_method: su
  become_flags: "-"
  block:

  - name: Whoami of root user
    import_tasks: ../../whoami/tasks/main.yml

  - name: Set timezone to Europe/Moscow
    community.general.timezone:
      name: Europe/Moscow

  - name: Disable swap
    command: swapoff -a
    changed_when: true
    when: ansible_swaptotal_mb > 0

  - name: Remove swap from fstab
    lineinfile:
      path: '/etc/fstab'
      regexp: '\sswap\s'
      state: 'absent'

  - name: Install dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common

  - name: Add Kubernetes APT repository key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Downloading the public signing key for the Kubernetes package repositories
    shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
  
  - name: Adding the appropriate Kubernetes apt repository.
    shell: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"
  
  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Install Kubernetes dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - kubeadm
      - kubelet
      - kubectl

  - name: Update apt packages
    apt:
      update_cache: yes
