- name: Started creating kubernetes cluster
  become: true
  become_user: root
  become_method: su
  become_flags: "-"
  block:

  - name: Whoami of root user
    import_tasks: ../../whoami/tasks/main.yml
